---
# Task to ensure that firewalld is correctly installed on Rocky Linux
- name: Ensure firewalld is installed on Rocky Linux
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "RedHat"

# Task to ensure that firewalld is correctly installed on Ubuntu
- name: Ensure firewalld is installed on Ubuntu
  ansible.builtin.apt:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "Debian"

#Task to open the ports for Tomcat Server
- name: Open the ports for Tomcat Server
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 8080
    - 8443
  when: ansible_facts['os_family'] == "RedHat"