---
- name: Ensure firewalld is installed on Rocky Linux
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure firewalld is installed on Ubuntu
  ansible.builtin.apt:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Open the port for Tomcat Server on Rocky Linux
  ansible.builtin.firewalld:
    port: "8080/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Open the port for Apache on Ubuntu
  ansible.builtin.firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_facts['os_family'] == "Debian"