---
# Update all packages in Ubuntu server
- name: Update all packages to the latest version using APT
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
  become: yes
  when: ansible_distribution == 'Ubuntu'
  notify: reboot  

# Update all packages in Rocky server
- name: Update all packages to the latest version using YUM
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  notify: reboot